[package]
name = "dht"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
futures = "0.3"
indexmap = "2.10.0"
quinn = "0.11.8"
rand = "0.9.2"
tarpc = { version = "0.36", features = ["tokio1"] }
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
